[project]
name = "iwpc"
version = "0.11.1"
authors = [
  { name="Jeremy J. H. Wilkinson", email="jero.wilkinson@gmail.com" },
]
description = "A framework for divergence based inference and detector response modelling for experimental physics"
readme = "PYPI_README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "torch",
    "lightning",
    "matplotlib",
    "pandas",
    "pyarrow",
    "scikit-learn",
    "tensorboard",
    "seaborn",
    "bokeh",
]

[project.urls]
Homepage = "https://github.com/jjhwilkinson/iwpc"
